{"entities": {"annotations": [{"start": 31, "end": 35, "probability": 0.957, "type": "Place", "normalized_text": "China"}], "urls": [{"start": 111, "end": 134, "url": "https://t.co/r99gLjj8bM", "expanded_url": "https://www.worldometers.info/coronavirus/worldwide-graphs/#case-timeline", "display_url": "worldometers.info/coronavirus/wo\u2026"}], "mentions": [{"start": 0, "end": 13, "username": "Worldometers", "id": "345301111"}]}, "created_at": "2020-04-08T09:19:56.000Z", "source": "Twitter for iPhone", "public_metrics": {"retweet_count": 0, "reply_count": 0, "like_count": 0, "quote_count": 0}, "author_id": "460880967", "reply_settings": "everyone", "text": "@Worldometers \u201cOn February 12, China reported 51,152 additional new cases due to\u2026\u201dwrong here, should be 15152. https://t.co/r99gLjj8bM", "in_reply_to_user_id": "345301111", "conversation_id": "1246336010784563201", "lang": "en", "referenced_tweets": [{"type": "replied_to", "id": "1246336010784563201"}], "possibly_sensitive": false, "id": "1247816438578130944"}